// prisma/seed.ts
import { PrismaClient } from "@prisma/client";
import { PostStatus, TableName } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("Début du peuplement des permissions...");

  // Supprimer les permissions existantes
  await prisma.permission.deleteMany();
  console.log("Anciennes permissions supprimées");

  // Définition des permissions par poste
  const permissionsData = [
    {
      post: PostStatus.ADMIN,
      tables: [
        {
          table: TableName.USER,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.CLINIQUE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.CLIENT,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.VISITE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.ACTIVITE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.LIEU,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.POST,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.PRESTATION,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.PRODUIT,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.EXAMEN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.GYNECOLOGIE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.IST,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.INFERTILITE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.MEDECINE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.VBG,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.GROSSESSE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.OBSTETRIQUE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.ACCOUCHEMENT,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.CPON,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.TEST_GROSSESSE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.SAA,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.DEPISTAGE_VIH,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.PEC_VIH,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.REFERENCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.CONTRE_REFERENCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.ORDONNANCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.ECHOGRAPHIE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.FACTURE_PRESTATION,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.FACTURE_PRODUIT,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.FACTURE_EXAMEN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.FACTURE_ECHOGRAPHIE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.PLANNING,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.CONSTANTE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.COMMANDE_FOURNISSEUR,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.DETAIL_COMMANDE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.BILAN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.TARIF_PRESTATION,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.TARIF_PRODUIT,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.ANOMALIE_INVENTAIRE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.TARIF_EXAMEN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.TARIF_ECHOGRAPHIE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.RESULTAT_EXAMEN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.RESULTAT_ECHOGRAPHIE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.DEMANDE_EXAMEN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.DEMANDE_ECHOGRAPHIE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.REFERENCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.ORDONNANCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.REGION,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.PERMISSION,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
      ],
    },
    {
      post: PostStatus.MEDECIN,
      tables: [
        {
          table: TableName.USER,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.CLINIQUE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.CLIENT,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.VISITE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.ACTIVITE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.LIEU,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.POST,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PRESTATION,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PRODUIT,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.EXAMEN,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.GYNECOLOGIE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.IST,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.INFERTILITE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.MEDECINE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.VBG,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.GROSSESSE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.OBSTETRIQUE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.ACCOUCHEMENT,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.CPON,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.TEST_GROSSESSE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.SAA,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.DEPISTAGE_VIH,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.PEC_VIH,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.REFERENCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.CONTRE_REFERENCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.ORDONNANCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.ECHOGRAPHIE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.FACTURE_PRESTATION,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.FACTURE_PRODUIT,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.FACTURE_EXAMEN,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.FACTURE_ECHOGRAPHIE,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PLANNING,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.CONSTANTE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.COMMANDE_FOURNISSEUR,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.DETAIL_COMMANDE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.BILAN,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.TARIF_PRESTATION,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.TARIF_PRODUIT,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.ANOMALIE_INVENTAIRE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.TARIF_EXAMEN,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.TARIF_ECHOGRAPHIE,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.RESULTAT_EXAMEN,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.RESULTAT_ECHOGRAPHIE,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.DEMANDE_EXAMEN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.DEMANDE_ECHOGRAPHIE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.REFERENCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.ORDONNANCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.REGION,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PERMISSION,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
      ],
    },
    {
      post: PostStatus.INFIRMIER,
      tables: [
        {
          table: TableName.USER,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.CLINIQUE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.CLIENT,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.VISITE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.ACTIVITE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.LIEU,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.POST,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PRESTATION,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PRODUIT,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.EXAMEN,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.GYNECOLOGIE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.IST,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.INFERTILITE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.MEDECINE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.VBG,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.GROSSESSE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.OBSTETRIQUE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.ACCOUCHEMENT,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.CPON,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.TEST_GROSSESSE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.SAA,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.DEPISTAGE_VIH,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.PEC_VIH,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.REFERENCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.CONTRE_REFERENCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.ORDONNANCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.ECHOGRAPHIE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.FACTURE_PRESTATION,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.FACTURE_PRODUIT,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.FACTURE_EXAMEN,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.FACTURE_ECHOGRAPHIE,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PLANNING,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.CONSTANTE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.COMMANDE_FOURNISSEUR,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.DETAIL_COMMANDE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.BILAN,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.TARIF_PRESTATION,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.TARIF_PRODUIT,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.ANOMALIE_INVENTAIRE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.TARIF_EXAMEN,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.TARIF_ECHOGRAPHIE,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.RESULTAT_EXAMEN,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.RESULTAT_ECHOGRAPHIE,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.DEMANDE_EXAMEN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.DEMANDE_ECHOGRAPHIE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.REFERENCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.ORDONNANCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.REGION,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PERMISSION,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
      ],
    },
    {
      post: PostStatus.SAGE_FEMME,
      tables: [
        {
          table: TableName.USER,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.CLINIQUE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.CLIENT,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.VISITE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.ACTIVITE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.LIEU,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.POST,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PRESTATION,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PRODUIT,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.EXAMEN,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.GYNECOLOGIE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.IST,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.INFERTILITE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.MEDECINE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.VBG,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.GROSSESSE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.OBSTETRIQUE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.ACCOUCHEMENT,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.CPON,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.TEST_GROSSESSE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.SAA,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.DEPISTAGE_VIH,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.PEC_VIH,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.REFERENCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.CONTRE_REFERENCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.ORDONNANCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.ECHOGRAPHIE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.FACTURE_PRESTATION,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.FACTURE_PRODUIT,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.FACTURE_EXAMEN,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.FACTURE_ECHOGRAPHIE,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PLANNING,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.CONSTANTE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.COMMANDE_FOURNISSEUR,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.DETAIL_COMMANDE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.BILAN,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.TARIF_PRESTATION,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.TARIF_PRODUIT,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.ANOMALIE_INVENTAIRE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.TARIF_EXAMEN,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.TARIF_ECHOGRAPHIE,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.RESULTAT_EXAMEN,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.RESULTAT_ECHOGRAPHIE,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.DEMANDE_EXAMEN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.DEMANDE_ECHOGRAPHIE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.REFERENCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.ORDONNANCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.REGION,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PERMISSION,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
      ],
    },
    {
      post: PostStatus.LABORANTIN,
      tables: [
        {
          table: TableName.USER,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.CLINIQUE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.CLIENT,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.VISITE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.ACTIVITE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.LIEU,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.POST,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PRESTATION,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PRODUIT,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.EXAMEN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.GYNECOLOGIE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.IST,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.INFERTILITE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.MEDECINE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.VBG,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.GROSSESSE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.OBSTETRIQUE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.ACCOUCHEMENT,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.CPON,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.TEST_GROSSESSE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.SAA,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.DEPISTAGE_VIH,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PEC_VIH,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.REFERENCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.CONTRE_REFERENCE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.ORDONNANCE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.ECHOGRAPHIE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.FACTURE_PRESTATION,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.FACTURE_PRODUIT,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.FACTURE_EXAMEN,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.FACTURE_ECHOGRAPHIE,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PLANNING,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.CONSTANTE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.COMMANDE_FOURNISSEUR,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.DETAIL_COMMANDE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.BILAN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.TARIF_PRESTATION,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.TARIF_PRODUIT,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.ANOMALIE_INVENTAIRE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.TARIF_EXAMEN,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.TARIF_ECHOGRAPHIE,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.RESULTAT_EXAMEN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.RESULTAT_ECHOGRAPHIE,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.DEMANDE_EXAMEN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.DEMANDE_ECHOGRAPHIE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.REFERENCE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.ORDONNANCE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.REGION,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PERMISSION,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
      ],
    },
    {
      post: PostStatus.CONSEILLER,
      tables: [
        {
          table: TableName.USER,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.CLINIQUE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.CLIENT,
          canCreate: true,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.VISITE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.ACTIVITE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.LIEU,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.POST,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PRESTATION,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PRODUIT,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.EXAMEN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.GYNECOLOGIE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.IST,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.INFERTILITE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.MEDECINE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.VBG,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.GROSSESSE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.OBSTETRIQUE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.ACCOUCHEMENT,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.CPON,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.TEST_GROSSESSE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.SAA,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.DEPISTAGE_VIH,
          canCreate: true,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PEC_VIH,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.REFERENCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.CONTRE_REFERENCE,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.ORDONNANCE,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.ECHOGRAPHIE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.FACTURE_PRESTATION,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.FACTURE_PRODUIT,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.FACTURE_EXAMEN,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.FACTURE_ECHOGRAPHIE,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PLANNING,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.CONSTANTE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.COMMANDE_FOURNISSEUR,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.DETAIL_COMMANDE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.BILAN,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.TARIF_PRESTATION,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.TARIF_PRODUIT,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.ANOMALIE_INVENTAIRE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.TARIF_EXAMEN,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.TARIF_ECHOGRAPHIE,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.RESULTAT_EXAMEN,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.RESULTAT_ECHOGRAPHIE,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.DEMANDE_EXAMEN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.DEMANDE_ECHOGRAPHIE,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.REFERENCE,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.ORDONNANCE,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.REGION,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PERMISSION,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
      ],
    },
    {
      post: PostStatus.CAISSIERE,
      tables: [
        {
          table: TableName.USER,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.CLINIQUE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.CLIENT,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.VISITE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.ACTIVITE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.LIEU,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.POST,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PRESTATION,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PRODUIT,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.EXAMEN,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.GYNECOLOGIE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.IST,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.INFERTILITE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.MEDECINE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.VBG,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.GROSSESSE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.OBSTETRIQUE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.ACCOUCHEMENT,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.CPON,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.TEST_GROSSESSE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.SAA,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.DEPISTAGE_VIH,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PEC_VIH,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.REFERENCE,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.CONTRE_REFERENCE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.ORDONNANCE,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.ECHOGRAPHIE,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.FACTURE_PRESTATION,
          canCreate: true,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.FACTURE_PRODUIT,
          canCreate: true,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.FACTURE_EXAMEN,
          canCreate: true,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.FACTURE_ECHOGRAPHIE,
          canCreate: true,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PLANNING,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.CONSTANTE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.COMMANDE_FOURNISSEUR,
          canCreate: true,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.DETAIL_COMMANDE,
          canCreate: true,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.BILAN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.TARIF_PRESTATION,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.TARIF_PRODUIT,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.ANOMALIE_INVENTAIRE,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.TARIF_EXAMEN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.TARIF_ECHOGRAPHIE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.RESULTAT_EXAMEN,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.RESULTAT_ECHOGRAPHIE,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.DEMANDE_EXAMEN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.DEMANDE_ECHOGRAPHIE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.REFERENCE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.ORDONNANCE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.REGION,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PERMISSION,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
      ],
    },
    {
      post: PostStatus.COMPTABLE,
      tables: [
        {
          table: TableName.USER,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.CLINIQUE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.CLIENT,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.VISITE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.ACTIVITE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.LIEU,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.POST,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PRESTATION,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.PRODUIT,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.EXAMEN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.GYNECOLOGIE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.IST,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.INFERTILITE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.MEDECINE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.VBG,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.GROSSESSE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.OBSTETRIQUE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.ACCOUCHEMENT,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.CPON,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.TEST_GROSSESSE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.SAA,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.DEPISTAGE_VIH,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PEC_VIH,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.REFERENCE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.CONTRE_REFERENCE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.ORDONNANCE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.ECHOGRAPHIE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.FACTURE_PRESTATION,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.FACTURE_PRODUIT,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.FACTURE_EXAMEN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.FACTURE_ECHOGRAPHIE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.PLANNING,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.CONSTANTE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.COMMANDE_FOURNISSEUR,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.DETAIL_COMMANDE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.BILAN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.TARIF_PRESTATION,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.TARIF_PRODUIT,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.ANOMALIE_INVENTAIRE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.TARIF_EXAMEN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.TARIF_ECHOGRAPHIE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.RESULTAT_EXAMEN,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.RESULTAT_ECHOGRAPHIE,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.DEMANDE_EXAMEN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.DEMANDE_ECHOGRAPHIE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.REFERENCE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.ORDONNANCE,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.REGION,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PERMISSION,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
      ],
    },
    {
      post: PostStatus.SUIVI_EVALLUATION,
      tables: [
        {
          table: TableName.USER,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.CLINIQUE,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.CLIENT,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.VISITE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.ACTIVITE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.LIEU,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.POST,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PRESTATION,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.PRODUIT,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.EXAMEN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.GYNECOLOGIE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.IST,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.INFERTILITE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.MEDECINE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.VBG,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.GROSSESSE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.OBSTETRIQUE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.ACCOUCHEMENT,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.CPON,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.TEST_GROSSESSE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.SAA,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.DEPISTAGE_VIH,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.PEC_VIH,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.REFERENCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.CONTRE_REFERENCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.ORDONNANCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.ECHOGRAPHIE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.FACTURE_PRESTATION,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.FACTURE_PRODUIT,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.FACTURE_EXAMEN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.FACTURE_ECHOGRAPHIE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.PLANNING,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.CONSTANTE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.COMMANDE_FOURNISSEUR,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.DETAIL_COMMANDE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.BILAN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.TARIF_PRESTATION,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.TARIF_PRODUIT,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.ANOMALIE_INVENTAIRE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.TARIF_EXAMEN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.TARIF_ECHOGRAPHIE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.RESULTAT_EXAMEN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.RESULTAT_ECHOGRAPHIE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.DEMANDE_EXAMEN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.DEMANDE_ECHOGRAPHIE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.REFERENCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.ORDONNANCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.REGION,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PERMISSION,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
      ],
    },
    {
      post: PostStatus.AMD,
      tables: [
        {
          table: TableName.USER,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.CLINIQUE,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.CLIENT,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.VISITE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.ACTIVITE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.LIEU,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.POST,
          canCreate: false,
          canRead: false,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PRESTATION,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.PRODUIT,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.EXAMEN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.GYNECOLOGIE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.IST,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.INFERTILITE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.MEDECINE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.VBG,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.GROSSESSE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.OBSTETRIQUE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.ACCOUCHEMENT,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.CPON,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.TEST_GROSSESSE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.SAA,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.DEPISTAGE_VIH,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.PEC_VIH,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.REFERENCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.CONTRE_REFERENCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.ORDONNANCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.ECHOGRAPHIE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
        {
          table: TableName.FACTURE_PRESTATION,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.FACTURE_PRODUIT,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.FACTURE_EXAMEN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.FACTURE_ECHOGRAPHIE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.PLANNING,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.CONSTANTE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.COMMANDE_FOURNISSEUR,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.DETAIL_COMMANDE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.BILAN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.TARIF_PRESTATION,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.TARIF_PRODUIT,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.ANOMALIE_INVENTAIRE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.TARIF_EXAMEN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.TARIF_ECHOGRAPHIE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.RESULTAT_EXAMEN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.RESULTAT_ECHOGRAPHIE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.DEMANDE_EXAMEN,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.DEMANDE_ECHOGRAPHIE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.REFERENCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.ORDONNANCE,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
        },
        {
          table: TableName.REGION,
          canCreate: false,
          canRead: true,
          canUpdate: false,
          canDelete: false,
        },
        {
          table: TableName.PERMISSION,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
        },
      ],
    },
  ];

  // Création des permissions
  for (const postData of permissionsData) {
    console.log(`Création des permissions pour le poste: ${postData.post}`);

    for (const tableData of postData.tables) {
      // Note: Cette section nécessite un userId valide pour fonctionner
      // Désactivé temporairement car postStatus n'existe pas dans le modèle Permission
      console.log(`[Désactivé] Permission pour ${tableData.table} avec droits: create=${tableData.canCreate}, read=${tableData.canRead}`);
    }

    console.log(`✓ Permissions créées pour ${postData.post}`);
  }

  console.log("✅ Peuplement des permissions terminé avec succès!");
}

main()
  .catch((e) => {
    console.error("Erreur lors du peuplement:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
