"use client";
// ecmis-02/lib/permissionData.ts
import { TableName } from "@prisma/client";

export const dataPermission = [
  {
    table: TableName.USER,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.CLINIQUE,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.CLIENT,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.VISITE,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.ACTIVITE,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.LIEU,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.POST,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.PRESTATION,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.PRODUIT,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.EXAMEN,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.GYNECOLOGIE,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.IST,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.INFERTILITE,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.MEDECINE,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.VBG,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.GROSSESSE,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.OBSTETRIQUE,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.ACCOUCHEMENT,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.CPON,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.TEST_GROSSESSE,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.SAA,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.DEPISTAGE_VIH,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.PEC_VIH,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.REFERENCE,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.CONTRE_REFERENCE,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.ORDONNANCE,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.ECHOGRAPHIE,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.FACTURE_PRESTATION,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.FACTURE_PRODUIT,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.FACTURE_EXAMEN,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.FACTURE_ECHOGRAPHIE,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.PLANNING,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.CONSTANTE,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.COMMANDE_FOURNISSEUR,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.DETAIL_COMMANDE,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.BILAN,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.TARIF_PRESTATION,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.TARIF_PRODUIT,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.ANOMALIE_INVENTAIRE,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.TARIF_EXAMEN,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.TARIF_ECHOGRAPHIE,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.RESULTAT_EXAMEN,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.RESULTAT_ECHOGRAPHIE,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.DEMANDE_EXAMEN,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.DEMANDE_ECHOGRAPHIE,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.ORDONNANCE,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.REGION,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.CLIENT_VIH,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.IMPORT_CLIENT_VIH,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.STOCK_PRODUIT,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.PERMISSION,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.ADMINISTRATION,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.AJUSTEMENT_STOCK,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.DETAIL_INVENTAIRE,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
  {
    table: TableName.INVENTAIRE,
    canCreate: false,
    canRead: false,
    canUpdate: false,
    canDelete: false,
  },
];
